import { registerSwarmHandlers } from './swarm';
import type { IpcContext } from './context';
import { registerChatHandlers } from './chat';
import { registerChatDeprecatedHandlers } from './chat-deprecated';
import { registerAgentsHandlers } from './agents';
import { registerSchedulerHandlers } from './scheduler';
import { registerSystemHandlers } from './system';
import { registerSettingsHandlers } from './settings';
import { registerIntegrationsHandlers } from './integrations';
import { registerLocalLlmHandlers } from './local-llm';
import { registerCodexHandlers } from './codex';
import { registerKimiHandlers } from './kimi';
import { registerGrokHandlers } from './grok';
import { registerTerminalHandlers } from './terminal';
import { registerClaudeCliHandlers } from './claude-cli';
import { registerKnowledgeHandlers } from './knowledge';
import { registerHarnessHandlers } from './harness';
import { registerEnrichHandlers } from './enrich';
import { registerPipelineHandlers } from './pipeline';
import { registerMgraphHandlers } from './mgraph';
import { registerOpenDesignHandlers } from './open-design';
import { registerActivityHandlers } from './activity';
import { registerDriveHandlers } from './drive';
import { registerRepoGraphHandlers } from './repo-graph';
import { registerDynamicWorkflowHandlers } from './dynamic-workflow';
import { registerKanbanHandlers } from './kanban';

export function registerAllIpcHandlers(ctx: IpcContext): void {
  registerSwarmHandlers(ctx);
  registerChatHandlers(ctx);
  registerChatDeprecatedHandlers(ctx);
  registerAgentsHandlers(ctx);
  registerSchedulerHandlers(ctx);
  registerSystemHandlers(ctx);
  registerSettingsHandlers(ctx);
  registerIntegrationsHandlers(ctx);
  registerLocalLlmHandlers(ctx);
  registerCodexHandlers(ctx);
  registerKimiHandlers(ctx);
  registerGrokHandlers(ctx);
  registerTerminalHandlers(ctx);
  registerClaudeCliHandlers(ctx);
  registerKnowledgeHandlers(ctx);
  registerHarnessHandlers(ctx);
  registerEnrichHandlers(ctx);
  registerPipelineHandlers(ctx);
  registerMgraphHandlers(ctx);
  registerOpenDesignHandlers(ctx);
  registerActivityHandlers(ctx);
  registerDriveHandlers(ctx);
  registerRepoGraphHandlers(ctx);
  registerDynamicWorkflowHandlers(ctx);
  registerKanbanHandlers(ctx);
}
