import type Database from 'better-sqlite3';

const OLD_SECTION = `## Green-check objetivo por rodada (host; obrigatorio no dev-loop)

Os validadores de codigo sao ESTATICOS (so LEEM): convergir contando SO os findings deles deixa a sprint convergir mesmo com typecheck/test VERMELHO. Por isso o workflow.js que voce gera DEVE, em cada rodada do dev-loop (apos o coder e o fix da rodada), chamar a primitiva HOST greenCheck() e MESCLAR os findings dela no MESMO set de convergencia que o devBlockersOf consome, ANTES dele:
- greenCheck(arg) e NAO-BLOQUEANTE: o HOST roda typecheck + test (e build quando o projeto tem build script E a rodada e candidata a convergencia, via arg.final===true) e devolve { ok, findings, checks } SEM dar throw. Vermelho do host = finding P1 deterministico; nunca aborta o run (ao contrario de gate(mode:'auto')).
- A primitiva esta no ctx ao lado de validateSprintPlan/materializeSprintPlan (mesma familia). NAO use shell do agente para isso: o green-check roda no HOST e e runtime-agnostico (o node nao precisa de Bash).
- greenCheck() devolve findings CRUS no formato { severity, where, problem, fix } (nao um grupo). O dedupeFindings itera GRUPOS com .findings; para nao engolir os findings do host, embrulhe-os como um GRUPO: const findings = dedupeFindings([...validators, { findings: greenCheckFindings }]). Mesclar findings crus direto (...greenCheckFindings) faz o dedupe ignora-los e o vermelho do host some - o oposto do objetivo.
- Posicao EXATA no loop: rode greenCheck e mescle ANTES de calcular const blockers = devBlockersOf(findings). Build caro (monorepo) NAO roda toda rodada: passe arg.final===true SO na rodada candidata a convergencia (quando os validadores read-only ja zeraram bloqueio), senao arg.final fica false (so typecheck+test).
Sem esse merge, a sprint converge so porque os validadores read-only nao acharam P1 - mesmo com o green-check vermelho. O finding do host entra no MESMO set que o devBlockersOf consome.

## Regras do workflow.js (subset ESM restrito)`;

const NEW_SECTION = `## Green-check objetivo por rodada (host; gate DETERMINISTICO, obrigatorio no dev-loop)

Os validadores de codigo sao ESTATICOS (so LEEM): convergir contando SO os findings deles deixa a sprint convergir mesmo com typecheck/test VERMELHO. Por isso o workflow.js que voce gera DEVE, em cada rodada do dev-loop (apos o coder e o fix da rodada), chamar a primitiva HOST greenCheck() e usar o seu green.ok como GATE DETERMINISTICO da convergencia (uma das duas condicoes do AND, ver secao seguinte):
- greenCheck(arg) e NAO-BLOQUEANTE: o HOST roda typecheck + test (e build quando o projeto tem build script E a rodada e candidata a convergencia, via arg.final===true) e devolve { ok, findings, checks } SEM dar throw. green.ok===true SO quando TODOS os checks rodados passaram (veredito endurecido: crash/spawn-fail/sinal/timeout/typecheck-test-VERMELHO => green.ok===false). Nunca aborta o run (ao contrario de gate(mode:'auto')).
- A primitiva esta no ctx ao lado de validateSprintPlan/materializeSprintPlan (mesma familia). NAO use shell do agente para isso: o green-check roda no HOST e e runtime-agnostico (o node nao precisa de Bash).
- green.ok e a REALIDADE OBJETIVA do build - e um gate DETERMINISTICO SEPARADO, nunca refutavel: os greenCheckFindings (green.findings, formato { severity, where, problem, fix }) NAO entram no refuter (nenhum LLM pode descarta-los como 'ruido'). Eles alimentam DIRETO o set de fix da rodada (concatena com os refutados-reais dos validadores), para o coder consertar o build vermelho.
- Posicao EXATA no loop: rode greenCheck DEPOIS dos validadores e ANTES de decidir a convergencia. Build caro (monorepo) NAO roda toda rodada: passe arg.final===true SO na rodada candidata a convergencia (quando os validadores read-only ja zeraram bloqueio), senao arg.final fica false (so typecheck+test).
- BUILD na convergencia (obrigatorio): como a convergencia usa os REFUTADOS (nao a severidade CRUA dos validadores), uma rodada pode ter rodado SEM build (final=false porque havia P1/P2 cru) e mesmo assim zerar os bloqueantes depois que o refuter descarta o ruido. Por isso, ANTES de quebrar o loop, se a rodada NAO incluiu build, rode um green-check FINAL (greenCheck({ final: true })) e exija green.ok===true: senao a sprint convergiria com o build NUNCA rodado (entrega que nao builda). Os findings desse green-check final alimentam o fix.
Sem usar green.ok como gate proprio, a sprint converge so porque os validadores read-only nao acharam P1 - mesmo com o green-check VERMELHO. A condicao de break DEVE incluir green.ok===true como AND independente (ver secao seguinte).

## Refute por evidencia + convergencia P1+P2 confirmado (host; obrigatorio no dev-loop)

Os findings crus dos validadores read-only sao PALPITE (eles leem o codigo e adivinham, sem rodar): convergir contando-os direto deixa o ruido inflar o loop (e por isso a convergencia antiga travava SO P1, para nao ficar em whack-a-mole de "major" regenerado toda rodada). Em vez disso, o workflow.js que voce gera DEVE, em cada rodada do dev-loop, rodar 1 no REFUTER (read-only, batch) que JULGA SO os findings dos validadores por EVIDENCIA antes da convergencia. O refuter e o seed read-only de refute do squad dynamic-workflow (DISTINTO dos validadores de codigo); o chamador informa o id exato no prompt, exatamente como faz com o planner e os validadores.
- O refuter julga SO os findings dos VALIDADORES read-only (palpite). A saida do green-check do host (realidade objetiva) NAO passa pelo refuter - vai como CONTEXTO-PROVA no prompt (para o refuter ancorar evidencia), mas os greenCheckFindings nunca sao refutados nem descartados. Passe ao refuter (read-only, schema schemas/refute.schema.json) os findings crus dos validadores + a saida do green-check do host como contexto + o codigo citado; ele devolve, por finding, { ref, verdict ('real'|'ruido'), evidencia, severityConfirmada } no REFUTE_SCHEMA (objeto de topo com array refutations). 1 no refuter por sprint/rodada (batch deterministico), NUNCA K refutadores. Emita no pacote o ARQUIVO schemas/refute.schema.json (o REFUTE_SCHEMA), como ja faz para todo node com schemaRef; sem esse arquivo a materializacao do no refuter falha (schema-missing) e o run morre.
- A convergencia consome SO os REFUTADOS-REAIS dos validadores (verdict==='real'); o ruido (verdict==='ruido') e DESCARTADO por evidencia e nunca chega ao devBlockersOf. O refuter NAO rebaixa severidade: severityConfirmada e a severidade REPORTADA confirmada (P1 reportado e confirmado real -> severityConfirmada P1). O codigo que monta os refutados-reais e FAIL-CLOSED: ITERA os findings CRUS dos validadores (a fonte da severidade/problem/fix) e descarta um finding SO quando ha uma refutacao correlata (por where/ref, 1:1) com verdict==='ruido'. Um finding cru SEM refutacao correlata (o refuter nao o julgou, errou o 'ref', ou ha colisao de varios no mesmo where) e MANTIDO com a severidade CRUA, NUNCA rebaixado para o numero do LLM. Assim um refuter que erra o ref ou rebaixa um P1 real NAO some o blocker (fail-OPEN); no maximo deixa de descartar um ruido (seguro). A severidade e SEMPRE a reportada pelo validador; o 'ref' do refuter so escolhe O QUE descartar, nunca a nota.
- FAIL-CLOSED: agent() devolve null em QUALQUER falha recuperavel do node (schema-invalid/timeout/runtime/esgotamento de provedor). Um refuter null com findings de validador pendentes NAO pode auto-convergir a sprint: trate como NAO-convergencia (mantenha os findings crus dos validadores no fix). O refuter so e chamado quando ha findings de validador (sem eles, pula a chamada - nao ha nada a refutar).
- devBlockersOf passa a travar severityConfirmada em {P1,P2} (NAO mais P1-only): conta SO os refutados-reais dos validadores. P3 confirmado-real = advisory (nao trava; segue pro gate de entrega como contexto). O P2-bloqueante so volta JUNTO com o refuter (a SEQUENCIA OBRIGATORIA): sem o refuter matando o ruido, P2-bloqueante traria de volta o whack-a-mole; com ele, P2 real volta a travar (e o pedido: "tem que ter P1 e P2").
- CONVERGENCIA = AND de DUAS condicoes INDEPENDENTES (SPEC §4.3): (1) green-check do host VERDE (green.ok, gate deterministico) E (2) devBlockersOf(refutados-reais).length===0 (zero P1/P2 confirmado-real) E (3) o refuter nao falhou (fail-closed). So quebre o loop (converged) quando as TRES valem. green-check VERMELHO ou refuter falho NUNCA convergem, mesmo com zero finding de validador.
- O no refuter e read-only e ancorado ao objetivo (le o codigo + consome a saida deterministica do green-check do host), entao e runtime-agnostico: NAO precisa de shell. Materialize-o no manifest de dev (materializeSprintPlan ja o cria por sprint/rodada pela fabrica); o id segue o contrato (refuter-s{S}-r{R}).
Sem o refuter, a convergencia volta a contar palpite cru: ou afrouxa demais (P1-only para nao oscilar) ou trava de graca (P2 de ruido). O green-check deterministico e o refuter sao gates SEPARADOS: o primeiro garante a realidade do build, o segundo torna seguro travar P1+P2 reais dos validadores.

## Regras do workflow.js (subset ESM restrito)`;

const NEW_MARKER = 'green-check do host VERDE (green.ok, gate deterministico)';

export function applyMigrationV113(db: Database.Database): void {
  db.prepare(
    `UPDATE agents SET system_prompt = REPLACE(system_prompt, ?, ?)
       WHERE id = 'dynamic-workflow-builder'
         AND system_prompt LIKE ?
         AND system_prompt NOT LIKE ?`,
  ).run(OLD_SECTION, NEW_SECTION, `%${OLD_SECTION}%`, `%${NEW_MARKER}%`);
}
