
import fs from 'fs';
import path from 'path';
import { LIONCLAW_HELPER_TOKEN_ENV } from '../helper-identity';

export { CHAT_GATED_HELPER_IDS } from '../helper-identity';

export interface GenerateWrapperOptions {
  fetchHelperToken?: boolean;
  staticEnv?: Record<string, string>;
}

export function generateWrapper(
  serverId: string,
  command: string,
  args: string[],
  envKeys: string[],
  lionclawHome: string,
  options: GenerateWrapperOptions = {},
): string {
  const endpointFile = path.join(lionclawHome, 'runtime', 'ipc-endpoint.json');

  return `#!/usr/bin/env node
// AUTO-GENERATED by LionClaw codex-sdk/mcp-wrapper-generator.ts.
// Do not edit by hand. Edits are overwritten by syncCodexMcpConfig.
//
// Per-MCP wrapper for the Codex SDK transport. Fetches secrets from the
// LionClaw vault via local IPC at spawn time, then execs the real MCP
// stdio server with the fetched env injected on top of process.env.

'use strict';

const net = require('node:net');
const fs = require('node:fs');
const { spawn } = require('node:child_process');

const SERVER_ID = ${JSON.stringify(serverId)};
const COMMAND = ${JSON.stringify(command)};
const ARGS = ${JSON.stringify(args)};
const ENV_KEYS = ${JSON.stringify(envKeys)};
const ENDPOINT_FILE = ${JSON.stringify(endpointFile)};
// S3b (SPEC chat-context-reduction 0.7 item 5): quando true, busca um token de
// identidade de processo (mint_helper_token) e o injeta no env do MCP real.
// O VALOR do token nunca aparece neste arquivo nem no config.toml.
const FETCH_HELPER_TOKEN = ${JSON.stringify(options.fetchHelperToken === true)};
const HELPER_TOKEN_ENV = ${JSON.stringify(LIONCLAW_HELPER_TOKEN_ENV)};
// SPEC mcp-index-codex secao 3: env fixo (surface/lane) do processo do MCP
// real. Valores sao metadados de roteamento, nunca segredos.
const STATIC_ENV = ${JSON.stringify(options.staticEnv ?? {})};

function die(message, code) {
  process.stderr.write('[lionclaw-mcp-wrapper:' + SERVER_ID + '] ' + message + '\\n');
  process.exit(code == null ? 1 : code);
}

function readEndpoint() {
  let raw;
  try {
    raw = fs.readFileSync(ENDPOINT_FILE, 'utf8');
  } catch (err) {
    die('cannot read ipc-endpoint.json at ' + ENDPOINT_FILE + ': ' + (err && err.message ? err.message : String(err)), 2);
  }
  try {
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed.address !== 'string') {
      die('ipc-endpoint.json missing address field', 2);
    }
    return parsed;
  } catch (err) {
    die('ipc-endpoint.json is not valid JSON: ' + (err && err.message ? err.message : String(err)), 2);
  }
  return null;
}

// One-shot JSON-RPC round-trip against the LionClaw local IPC endpoint.
// Used by fetchEnv (get_mcp_env) and, for gated helpers, fetchHelperToken
// (mint_helper_token). Resolves with response.result; rejects on RPC error,
// invalid JSON or timeout.
function rpcOnce(method, params) {
  return new Promise((resolve, reject) => {
    const endpoint = readEndpoint();
    const socket = net.createConnection(endpoint.address);
    let buffer = '';
    let settled = false;

    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      try { socket.destroy(); } catch (_e) { /* ignore */ }
      reject(new Error(method + ' timeout for ' + SERVER_ID));
    }, 15000);

    socket.setEncoding('utf8');
    socket.on('connect', () => {
      const req = {
        jsonrpc: '2.0',
        id: 1,
        method: method,
        params: params,
      };
      socket.write(JSON.stringify(req) + '\\n');
    });
    socket.on('data', (chunk) => {
      buffer += chunk;
      const newlineIdx = buffer.indexOf('\\n');
      if (newlineIdx === -1) return;
      const line = buffer.slice(0, newlineIdx).trim();
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      try { socket.end(); } catch (_e) { /* ignore */ }
      let response;
      try {
        response = JSON.parse(line);
      } catch (err) {
        reject(new Error('invalid JSON from local IPC: ' + (err && err.message ? err.message : String(err))));
        return;
      }
      if (response && response.error) {
        const msg = response.error && response.error.message ? response.error.message : 'unknown error';
        reject(new Error('local IPC error: ' + msg));
        return;
      }
      resolve(response && response.result ? response.result : {});
    });
    socket.on('error', (err) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      reject(err);
    });
  });
}

function fetchEnv() {
  return rpcOnce('get_mcp_env', { server_id: SERVER_ID, caller_pid: process.pid })
    .then((result) => (result && result.env ? result.env : {}));
}

function fetchHelperToken() {
  return rpcOnce('mint_helper_token', { server_id: SERVER_ID, caller_pid: process.pid })
    .then((result) => (result && typeof result.token === 'string' ? result.token : ''));
}

async function main() {
  let fetched = {};
  if (ENV_KEYS.length > 0) {
    try {
      fetched = await fetchEnv();
    } catch (err) {
      die('failed to fetch env from LionClaw: ' + (err && err.message ? err.message : String(err)), 3);
    }
  }

  const childEnv = Object.assign({}, process.env);
  for (const key of ENV_KEYS) {
    if (fetched && Object.prototype.hasOwnProperty.call(fetched, key)) {
      childEnv[key] = fetched[key];
    }
  }

  for (const key of Object.keys(STATIC_ENV)) {
    childEnv[key] = STATIC_ENV[key];
  }

  if (FETCH_HELPER_TOKEN) {
    // S3b: identidade de processo do helper gated. TOLERANTE por design —
    // falha aqui NUNCA derruba o spawn: o helper roda anonimo (100% funcional
    // em shadow; no S4 apenas as chamadas gated ficam fail-closed).
    try {
      const token = await fetchHelperToken();
      if (token) {
        childEnv[HELPER_TOKEN_ENV] = token;
      } else {
        process.stderr.write('[lionclaw-mcp-wrapper:' + SERVER_ID + '] empty helper token; child runs anonymous\\n');
      }
    } catch (err) {
      process.stderr.write('[lionclaw-mcp-wrapper:' + SERVER_ID + '] helper token fetch failed (child runs anonymous): ' + (err && err.message ? err.message : String(err)) + '\\n');
    }
  }

  const child = spawn(COMMAND, ARGS, {
    stdio: ['inherit', 'inherit', 'inherit'],
    env: childEnv,
  });

  const forward = (signal) => {
    try { child.kill(signal); } catch (_e) { /* ignore */ }
  };
  process.on('SIGTERM', () => forward('SIGTERM'));
  process.on('SIGINT', () => forward('SIGINT'));

  child.on('error', (err) => {
    die('failed to spawn ' + COMMAND + ': ' + (err && err.message ? err.message : String(err)), 4);
  });

  child.on('exit', (code, signal) => {
    if (code != null) {
      process.exit(code);
    } else if (signal) {
      process.exit(128 + (typeof signal === 'number' ? signal : 15));
    } else {
      process.exit(0);
    }
  });
}

main();
`;
}

export async function writeWrapper(
  serverId: string,
  sourceContent: string,
  lionclawHome: string,
): Promise<string> {
  const dir = path.join(lionclawHome, 'mcp-wrappers');
  await fs.promises.mkdir(dir, { recursive: true });
  if (process.platform !== 'win32') {
    try {
      await fs.promises.chmod(dir, 0o700);
    } catch {
    }
  }
  const file = path.join(dir, `${serverId}.js`);
  await fs.promises.writeFile(file, sourceContent, { encoding: 'utf8' });
  if (process.platform !== 'win32') {
    try {
      await fs.promises.chmod(file, 0o700);
    } catch {
    }
  }
  return file;
}

export async function listWrappers(lionclawHome: string): Promise<string[]> {
  const dir = path.join(lionclawHome, 'mcp-wrappers');
  let entries: string[];
  try {
    entries = await fs.promises.readdir(dir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw err;
  }
  return entries.filter((n) => n.endsWith('.js')).map((n) => path.join(dir, n));
}

export async function deleteWrapper(filePath: string): Promise<void> {
  try {
    await fs.promises.unlink(filePath);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }
}
