import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const MAIN = join(__dirname, '..');
const RE_HANDLE = /ipcMain\.handle\(\s*['"]([^'"]+)['"]/g;
const RE_ON = /ipcMain\.on\s*\(/g;

function walk(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (p.endsWith('.ts')) out.push(p);
  }
  return out;
}

function sources(): string[] {
  const files = [join(MAIN, 'ipc-handlers.ts'), ...walk(join(MAIN, 'ipc'))];
  return files.map((f) => readFileSync(f, 'utf8'));
}

function channelNames(): string[] {
  const names: string[] = [];
  for (const src of sources()) {
    for (const m of src.matchAll(RE_HANDLE)) names.push(m[1]);
  }
  return names;
}

function countOnListeners(): number {
  let n = 0;
  for (const src of sources()) n += [...src.matchAll(RE_ON)].length;
  return n;
}

const GOLDEN: string[] = [
  'activity:get-blocks',
  'agents:create',
  'agents:delete',
  'agents:get',
  'agents:list',
  'agents:sync-to-orchestrator',
  'agents:update',
  'artifact:get-state',
  'artifact:set-state',
  'auth:enable-totp',
  'auth:is-authenticated',
  'auth:is-first-run',
  'auth:login',
  'auth:logout',
  'auth:setup-password',
  'auth:verify-totp',
  'channels:get',
  'channels:list',
  'channels:save-telegram',
  'channels:telegram-status',
  'channels:test-telegram',
  'channels:toggle',
  'chat:archive-session',
  'chat:ask-response',
  'chat:clear',
  'chat:clear-cancel',
  'chat:clear-session',
  'chat:compact-session',
  'chat:create-session',
  'chat:confirm-response',
  'chat:delete-session',
  'chat:ensure-session',
  'chat:get-active-session',
  'chat:get-context-usage',
  'chat:get-feature-toggles',
  'chat:get-messages',
  'chat:get-sessions',
  'chat:list-open-sessions',
  'chat:send',
  'chat:set-feature-toggles',
  'chat:set-session-orchestrator',
  'chat:stop',
  'codeburn:kill',
  'codeburn:resize',
  'codeburn:spawn',
  'codeburn:write',
  'codex:apply-prep',
  'codex:check-prep-needed',
  'codex:grant-consent',
  'codex:list-model-capabilities',
  'codex:open-login',
  'codex:set-binary-path',
  'codex:status',
  'codex:test',
  'kimi:open-login',
  'kimi:set-binary-path',
  'kimi:status',
  'kimi:test',
  'claude-cli:open-login',
  'claude-cli:set-binary-path',
  'claude-cli:status',
  'claude-cli:test',
  'dialog:open-directory',
  'dialog:open-file',
  'drive:assumir',
  'drive:get-state',
  'drive:resume',
  'drive:set-mode',
  'drive:start',
  'drive:stop',
  'dynamic-workflow:abort',
  'dynamic-workflow:approve-gate',
  'dynamic-workflow:closer-message',
  'dynamic-workflow:delete',
  'dynamic-workflow:finalize',
  'dynamic-workflow:get-artifacts',
  'dynamic-workflow:get-events',
  'dynamic-workflow:get-messages',
  'dynamic-workflow:get-nodes',
  'dynamic-workflow:get-run',
  'dynamic-workflow:get-run-bundle',
  'dynamic-workflow:get-snapshot',
  'dynamic-workflow:intervene',
  'dynamic-workflow:list-runs',
  'dynamic-workflow:open-run-dir',
  'dynamic-workflow:pause',
  'dynamic-workflow:reopen',
  'dynamic-workflow:request-replan',
  'dynamic-workflow:resolve-with-closer',
  'dynamic-workflow:resume',
  'dynamic-workflow:send-message',
  'dynamic-workflow:start',
  'dynamic-workflow:validate',
  'enrich:abort',
  'enrich:approve-phase',
  'enrich:delete',
  'enrich:finalize',
  'enrich:get-messages',
  'enrich:get-spec',
  'enrich:list-sessions',
  'enrich:open-spec',
  'enrich:resume-after-auth',
  'enrich:send',
  'enrich:start',
  'google:authenticate',
  'google:revoke',
  'google:setup',
  'google:status',
  'grok:logout',
  'grok:open-login',
  'grok:set-binary-path',
  'grok:status',
  'grok:test',
  'harness:abort',
  'harness:approve-sprints',
  'harness:create-project',
  'harness:delete-project',
  'harness:get-evaluation',
  'harness:get-feedback-audit',
  'harness:get-metrics',
  'harness:get-project',
  'harness:get-rounds',
  'harness:get-sprint-json',
  'harness:get-sprints',
  'harness:get-sprints-json',
  'harness:get-stream-log',
  'harness:list-projects',
  'harness:pause',
  'harness:plan',
  'harness:regenerate-sprints',
  'harness:resume',
  'harness:run',
  'higgsfield:auth-status',
  'higgsfield:connect',
  'higgsfield:disconnect',
  'image:edit',
  'image:generate',
  'kanban:archive-card',
  'kanban:attach-file',
  'kanban:create-board',
  'kanban:create-card',
  'kanban:delete-board',
  'kanban:delete-card',
  'kanban:deliver-card',
  'kanban:get-card',
  'kanban:list-boards',
  'kanban:move-card',
  'kanban:open-attachment',
  'kanban:query-cards',
  'kanban:read-attachment',
  'kanban:remove-attachment',
  'kanban:unarchive-card',
  'kanban:update-card',
  'knowledge:benchmark:start',
  'knowledge:benchmark:status',
  'knowledge:config:get',
  'knowledge:config:update',
  'knowledge:delete',
  'knowledge:list',
  'knowledge:reprocess',
  'knowledge:search',
  'knowledge:upload',
  'logs:export-csv',
  'logs:export-json',
  'logs:query',
  'logs:query-system',
  'mcp:create',
  'mcp:delete',
  'mcp:get-dist-stale',
  'mcp:list',
  'mcp:list-sdk',
  'mcp:refresh-sdk',
  'mcp:restart',
  'mcp:test',
  'mcp:toggle',
  'mcp:toggle-sdk',
  'mcp:update',
  'memory:get-summaries',
  'memory:get-working',
  'memory:search-semantic',
  'memory:trigger-compaction',
  'memory:update-working',
  'mgraph:delete-note',
  'mgraph:graph',
  'mgraph:ingest-accept',
  'mgraph:ingest-cancel',
  'mgraph:ingest-discard',
  'mgraph:ingest-estimate',
  'mgraph:ingest-file',
  'mgraph:ingest-history',
  'mgraph:ingest-resume',
  'mgraph:ingest-settings',
  'mgraph:ingest-settings-update',
  'mgraph:ingest-text',
  'mgraph:ingest-url',
  'mgraph:list-notes',
  'mgraph:note-backlinks',
  'mgraph:read',
  'mgraph:search',
  'mgraph:seed',
  'mgraph:stats',
  'ollama:check',
  'ollama:list-models',
  'ollama:listModels',
  'onboarding:is-completed',
  'onboarding:mark-completed',
  'onboarding:reset',
  'open-design:boot-install-retry',
  'open-design:boot-install-status',
  'open-design:build-initial-prompt',
  'open-design:destructive-unlock',
  'open-design:ensure-session',
  'open-design:get-locked-snapshot',
  'open-design:get-session-config',
  'open-design:get-start-status',
  'open-design:hide-view',
  'open-design:inject-initial-prompt',
  'open-design:lock',
  'open-design:open-artifact',
  'open-design:preflight',
  'open-design:read-locked-html',
  'open-design:restart',
  'open-design:set-session-config',
  'open-design:set-view-bounds',
  'open-design:setup',
  'open-design:show-view',
  'open-design:snapshot',
  'open-design:start',
  'open-design:status',
  'open-design:stop',
  'pipeline:abort',
  'pipeline:advance',
  'pipeline:approve',
  'pipeline:conclude',
  'pipeline:confirm-development',
  'pipeline:create-project',
  'pipeline:decided',
  'pipeline:delete-project',
  'pipeline:export-report',
  'pipeline:get-audit-agents-state',
  'pipeline:get-conversation-phases',
  'pipeline:get-phase-messages',
  'pipeline:get-project',
  'pipeline:get-reset-preview',
  'pipeline:get-security-agent-status',
  'pipeline:get-smoke-test-path',
  'pipeline:get-sprint-detail',
  'pipeline:get-sprint-history',
  'pipeline:list-projects',
  'pipeline:list-sprints',
  'pipeline:metrics',
  'pipeline:open-project-file',
  'pipeline:open-smoke-test',
  'pipeline:pause',
  'pipeline:read-manifest',
  'pipeline:read-phase-artifact',
  'pipeline:read-phase-document',
  'pipeline:report',
  'pipeline:reset-phase',
  'pipeline:reset-sprint',
  'pipeline:resume',
  'pipeline:resume-after-auth',
  'pipeline:retry',
  'pipeline:send',
  'pipeline:start',
  'pricing:calculate',
  'provider:check',
  'provider:connect',
  'provider:disconnect',
  'provider:list-statuses',
  'provider:test-connection',
  'provider:test-openai-compatible',
  'provider:test-vertex-ai',
  'repo-graph:add-repository',
  'repo-graph:attach-session',
  'repo-graph:build',
  'repo-graph:detach-session',
  'repo-graph:get-session-state',
  'repo-graph:list',
  'repo-graph:metrics',
  'repo-graph:remove-repository',
  'repo-graph:set-global-prompt-suppressed',
  'repo-graph:set-prompt-suppressed',
  'repo-graph:status',
  'repo-graph:update',
  'rules:get-agent',
  'rules:get-global',
  'rules:update-agent',
  'rules:update-global',
  'scheduler:cleanup-sessions',
  'scheduler:create',
  'scheduler:delete',
  'scheduler:delete-session',
  'scheduler:get-activities',
  'scheduler:get-activity-stats',
  'scheduler:get-all-tags',
  'scheduler:get-runs',
  'scheduler:get-sessions',
  'scheduler:list',
  'scheduler:pause',
  'scheduler:pending-count',
  'scheduler:resume',
  'scheduler:review-run',
  'scheduler:update',
  'settings:get',
  'settings:set-api-key',
  'settings:update',
  'shell:open-file',
  'shell:open-path',
  'shell:show-in-folder',
  'skills:create',
  'skills:delete',
  'skills:get',
  'skills:list',
  'skills:update',
  'skills:update-raw',
  'soul:get',
  'soul:update',
  'tasks:categories',
  'tasks:create',
  'tasks:delete',
  'tasks:get',
  'tasks:list',
  'tasks:pending-due-count',
  'tasks:update',
  'terminal:close',
  'terminal:open',
  'terminal:resize',
  'terminal:write',
  'tools:get-bypass',
  'tools:get-enabled',
  'tools:get-settings',
  'tools:get-telegram-armed',
  'tools:getEnabled',
  'tools:getSettings',
  'tools:set-bypass',
  'tools:set-enabled',
  'tools:set-telegram-armed',
  'tools:setEnabled',
  'usage:provider-limits',
  'user:get',
  'user:update',
  'vault:check',
  'vault:delete',
  'vault:health',
  'vault:list',
  'vault:register-and-set',
  'vault:set',
  'voice:list-cartesia-voices',
  'voice:list-voices',
  'voice:read-audio-file',
  'voice:speak',
  'voice:speak-cartesia',
  'voice:speak-live',
  'voice:transcribe',
];

describe('ipc channel list (gate de equivalencia do refactor)', () => {
  it('conjunto de nomes == golden (352, diff vazio)', () => {
    const names = channelNames();
    expect([...new Set(names)].sort()).toEqual([...GOLDEN].sort());
  });
  it('355 registros, 355 nomes unicos, 0 duplicatas', () => {
    const names = channelNames();
    expect(names.length).toBe(355);
    expect(new Set(names).size).toBe(355);
  });
  it('0 listeners ipcMain.on (so ipcMain.handle no projeto)', () => {
    expect(countOnListeners()).toBe(0);
  });
});
